[tox]
envlist = test,lint,type,coverage

[testenv]
deps = {[dev]deps}

[dev]
deps =
    autoflake~=2.3
    black~=26.1
    build~=1.4
    flake8~=7.3
    mypy~=1.19
    pre-commit~=4.5
    pytest~=9.0
    pytest-cov~=7.0
    tox~=4.34
    twine~=6.2
    types-PyYAML~=6.0
    types-requests~=2.32

[testenv:test]
commands = pytest tests/ -v --cov=nameping --cov-report=term-missing

[testenv:lint]
commands =
    flake8 src/nameping tests/
    black --check src/nameping tests/

[testenv:type]
commands = mypy src/nameping

[testenv:format]
commands =
    autoflake --in-place --remove-all-unused-imports --recursive src/nameping tests/
    black src/nameping tests/

[testenv:coverage]
commands = pytest tests/ -v --cov=nameping --cov-report=html --cov-report=term-missing

[flake8]
max-line-length = 88
extend-ignore = E203, E501
